import { createDefaultState, sanitizeState } from './state.js';

export const MOOD_PRESETS = [
  {
    id: 'ancient-gold',
    name: 'Ancient Gold',
    state: {
      pattern: 'flower-of-life',
      complexity: 4,
      scale: 88,
      rotation: 0,
      symmetry: 12,
      strokeWidth: 2.2,
      strokeColor: '#d9a84f',
      secondaryColor: '#7a4b25',
      fillEnabled: true,
      fillOpacity: 0.08,
      strokeOpacity: 0.92,
      glowStrength: 4.5,
      overlayEnabled: true,
      overlayPattern: 'metatrons-cube',
      overlayOpacity: 0.18,
      overlayScale: 80,
      overlayComplexity: 5,
      overlaySymmetry: 12,
      overlayRotation: 30,
      centerSymbolEnabled: true,
      backgroundPreset: 'cosmic-dark',
      backgroundColor1: '#151020',
      backgroundColor2: '#030308',
      vignette: true,
      grain: true,
    },
  },
  {
    id: 'cosmic-violet',
    name: 'Cosmic Violet',
    state: {
      pattern: 'radial-mandala',
      complexity: 5,
      scale: 92,
      rotation: 8,
      symmetry: 16,
      strokeWidth: 1.7,
      strokeColor: '#c6a3ff',
      secondaryColor: '#58d7ff',
      fillEnabled: true,
      fillOpacity: 0.1,
      strokeOpacity: 0.88,
      glowStrength: 9,
      overlayEnabled: true,
      overlayPattern: 'flower-of-life',
      overlayOpacity: 0.16,
      overlayScale: 118,
      overlayComplexity: 5,
      overlaySymmetry: 12,
      overlayRotation: 15,
      centerSymbolEnabled: true,
      backgroundPreset: 'radial-gradient',
      backgroundColor1: '#251545',
      backgroundColor2: '#02030a',
      vignette: true,
      grain: true,
    },
  },
  {
    id: 'monk-ink',
    name: 'Monk Ink',
    state: {
      pattern: 'sri-yantra',
      complexity: 3,
      scale: 84,
      rotation: 0,
      symmetry: 9,
      strokeWidth: 2,
      strokeColor: '#252015',
      secondaryColor: '#765c35',
      fillEnabled: false,
      fillOpacity: 0.02,
      strokeOpacity: 0.84,
      glowStrength: 0,
      overlayEnabled: true,
      overlayPattern: 'vesica-piscis',
      overlayOpacity: 0.14,
      overlayScale: 76,
      overlayComplexity: 4,
      overlaySymmetry: 9,
      overlayRotation: 0,
      centerSymbolEnabled: true,
      backgroundPreset: 'paper-light',
      backgroundColor1: '#e2d5b9',
      backgroundColor2: '#ad9b78',
      vignette: true,
      grain: true,
    },
  },
  {
    id: 'solar-flare',
    name: 'Solar Flare',
    state: {
      pattern: 'star-grid',
      complexity: 5,
      scale: 90,
      rotation: 18,
      symmetry: 14,
      strokeWidth: 2.5,
      strokeColor: '#ffbe57',
      secondaryColor: '#e04f2f',
      fillEnabled: true,
      fillOpacity: 0.12,
      strokeOpacity: 0.92,
      glowStrength: 8,
      overlayEnabled: true,
      overlayPattern: 'radial-mandala',
      overlayOpacity: 0.2,
      overlayScale: 82,
      overlayComplexity: 5,
      overlaySymmetry: 14,
      overlayRotation: 7,
      centerSymbolEnabled: true,
      backgroundPreset: 'linear-gradient',
      backgroundColor1: '#2c0f18',
      backgroundColor2: '#070308',
      vignette: true,
      grain: true,
    },
  },
  {
    id: 'deep-space',
    name: 'Deep Space',
    state: {
      pattern: 'metatrons-cube',
      complexity: 5,
      scale: 90,
      rotation: 0,
      symmetry: 12,
      strokeWidth: 1.4,
      strokeColor: '#8fe5ff',
      secondaryColor: '#6b73ff',
      fillEnabled: false,
      fillOpacity: 0.04,
      strokeOpacity: 0.78,
      glowStrength: 10,
      overlayEnabled: true,
      overlayPattern: 'star-grid',
      overlayOpacity: 0.24,
      overlayScale: 126,
      overlayComplexity: 5,
      overlaySymmetry: 12,
      overlayRotation: 15,
      centerSymbolEnabled: false,
      backgroundPreset: 'cosmic-dark',
      backgroundColor1: '#06152b',
      backgroundColor2: '#000209',
      vignette: true,
      grain: true,
    },
  },
  {
    id: 'nordic-frost',
    name: 'Nordic Frost',
    state: {
      pattern: 'seed-of-life',
      complexity: 4,
      scale: 82,
      rotation: 30,
      symmetry: 12,
      strokeWidth: 1.8,
      strokeColor: '#d8f7ff',
      secondaryColor: '#7bc2d0',
      fillEnabled: true,
      fillOpacity: 0.08,
      strokeOpacity: 0.9,
      glowStrength: 5.5,
      overlayEnabled: true,
      overlayPattern: 'star-grid',
      overlayOpacity: 0.16,
      overlayScale: 74,
      overlayComplexity: 4,
      overlaySymmetry: 12,
      overlayRotation: 0,
      centerSymbolEnabled: true,
      backgroundPreset: 'radial-gradient',
      backgroundColor1: '#102a33',
      backgroundColor2: '#02060a',
      vignette: true,
      grain: false,
    },
  },
  {
    id: 'black-paper',
    name: 'Black Paper',
    state: {
      pattern: 'sri-yantra',
      complexity: 4,
      scale: 86,
      rotation: 0,
      symmetry: 12,
      strokeWidth: 1.8,
      strokeColor: '#d6c19a',
      secondaryColor: '#8d7a55',
      fillEnabled: false,
      fillOpacity: 0.03,
      strokeOpacity: 0.86,
      glowStrength: 1.5,
      overlayEnabled: true,
      overlayPattern: 'flower-of-life',
      overlayOpacity: 0.12,
      overlayScale: 78,
      overlayComplexity: 4,
      overlaySymmetry: 12,
      overlayRotation: 0,
      centerSymbolEnabled: true,
      backgroundPreset: 'black-paper',
      backgroundColor1: '#10100d',
      backgroundColor2: '#020202',
      vignette: true,
      grain: true,
    },
  },
  {
    id: 'psychedelic-aura',
    name: 'Psychedelic Aura',
    state: {
      pattern: 'radial-mandala',
      complexity: 6,
      scale: 96,
      rotation: 11,
      symmetry: 18,
      strokeWidth: 1.6,
      strokeColor: '#64ffd8',
      secondaryColor: '#f878ff',
      fillEnabled: true,
      fillOpacity: 0.16,
      strokeOpacity: 0.92,
      glowStrength: 11,
      overlayEnabled: true,
      overlayPattern: 'vesica-piscis',
      overlayOpacity: 0.24,
      overlayScale: 132,
      overlayComplexity: 6,
      overlaySymmetry: 18,
      overlayRotation: 28,
      centerSymbolEnabled: true,
      backgroundPreset: 'cosmic-dark',
      backgroundColor1: '#251349',
      backgroundColor2: '#031116',
      vignette: true,
      grain: false,
    },
  },
  {
    id: 'white-marble',
    name: 'White Marble',
    state: {
      pattern: 'flower-of-life',
      complexity: 5,
      scale: 88,
      rotation: 0,
      symmetry: 12,
      strokeWidth: 1.6,
      strokeColor: '#8c6c3d',
      secondaryColor: '#b9a071',
      fillEnabled: true,
      fillOpacity: 0.06,
      strokeOpacity: 0.84,
      glowStrength: 0,
      overlayEnabled: true,
      overlayPattern: 'sri-yantra',
      overlayOpacity: 0.16,
      overlayScale: 80,
      overlayComplexity: 5,
      overlaySymmetry: 12,
      overlayRotation: 0,
      centerSymbolEnabled: true,
      backgroundPreset: 'white-marble',
      backgroundColor1: '#f5f0e7',
      backgroundColor2: '#c8c1b2',
      vignette: true,
      grain: true,
    },
  },
  {
    id: 'copper-engraving',
    name: 'Copper Engraving',
    state: {
      pattern: 'metatrons-cube',
      complexity: 4,
      scale: 88,
      rotation: 0,
      symmetry: 12,
      strokeWidth: 1.5,
      strokeColor: '#c97d45',
      secondaryColor: '#6f3a22',
      fillEnabled: false,
      fillOpacity: 0.04,
      strokeOpacity: 0.9,
      glowStrength: 3,
      overlayEnabled: true,
      overlayPattern: 'star-grid',
      overlayOpacity: 0.18,
      overlayScale: 116,
      overlayComplexity: 5,
      overlaySymmetry: 12,
      overlayRotation: 30,
      centerSymbolEnabled: true,
      backgroundPreset: 'black-paper',
      backgroundColor1: '#160f0c',
      backgroundColor2: '#020101',
      vignette: true,
      grain: true,
    },
  },
];

const RANDOM_PALETTES = [
  {
    strokeColor: '#d9a84f',
    secondaryColor: '#7a4b25',
    backgroundPreset: 'cosmic-dark',
    backgroundColor1: '#151020',
    backgroundColor2: '#030308',
    glowStrength: 4.5,
  },
  {
    strokeColor: '#c6a3ff',
    secondaryColor: '#58d7ff',
    backgroundPreset: 'radial-gradient',
    backgroundColor1: '#251545',
    backgroundColor2: '#02030a',
    glowStrength: 8,
  },
  {
    strokeColor: '#ffbe57',
    secondaryColor: '#e04f2f',
    backgroundPreset: 'linear-gradient',
    backgroundColor1: '#2c0f18',
    backgroundColor2: '#070308',
    glowStrength: 7,
  },
  {
    strokeColor: '#8fe5ff',
    secondaryColor: '#6b73ff',
    backgroundPreset: 'cosmic-dark',
    backgroundColor1: '#06152b',
    backgroundColor2: '#000209',
    glowStrength: 9,
  },
  {
    strokeColor: '#c97d45',
    secondaryColor: '#6f3a22',
    backgroundPreset: 'black-paper',
    backgroundColor1: '#160f0c',
    backgroundColor2: '#020101',
    glowStrength: 2.5,
  },
  {
    strokeColor: '#d8f7ff',
    secondaryColor: '#7bc2d0',
    backgroundPreset: 'radial-gradient',
    backgroundColor1: '#102a33',
    backgroundColor2: '#02060a',
    glowStrength: 5,
  },
];

const PATTERN_IDS = [
  'flower-of-life',
  'seed-of-life',
  'metatrons-cube',
  'vesica-piscis',
  'sri-yantra',
  'radial-mandala',
  'star-grid',
];

export function applyMoodPreset(currentState, presetId) {
  const preset = MOOD_PRESETS.find((item) => item.id === presetId) ?? MOOD_PRESETS[0];
  return sanitizeState({
    ...currentState,
    ...preset.state,
    moodPreset: preset.id,
  });
}

export function generateVariation(seed) {
  const random = createSeededRandom(seed);
  const base = createDefaultState();
  const palette = pick(RANDOM_PALETTES, random);
  const pattern = pick(PATTERN_IDS, random);
  const overlayPattern = pick(PATTERN_IDS.filter((item) => item !== pattern), random);

  return sanitizeState({
    ...base,
    ...palette,
    seed,
    moodPreset: 'custom',
    pattern,
    overlayPattern,
    complexity: randomInt(random, 3, 6),
    scale: randomInt(random, 78, 100),
    rotation: randomInt(random, 0, 11) * 5,
    symmetry: randomInt(random, 8, 18),
    strokeWidth: Number((1.2 + random() * 2.2).toFixed(1)),
    strokeOpacity: Number((0.72 + random() * 0.22).toFixed(2)),
    fillEnabled: random() > 0.28,
    fillOpacity: Number((0.04 + random() * 0.14).toFixed(2)),
    glowStrength: Number(Math.min(12, palette.glowStrength + random() * 2.5).toFixed(1)),
    centerEmphasis: random() > 0.18,
    overlayEnabled: random() > 0.12,
    overlayOpacity: Number((0.12 + random() * 0.16).toFixed(2)),
    overlayScale: randomInt(random, 68, 148),
    overlayComplexity: randomInt(random, 3, 6),
    overlaySymmetry: randomInt(random, 8, 18),
    overlayRotation: randomInt(random, 0, 11) * 15,
    centerSymbolEnabled: random() > 0.24,
    vignette: true,
    grain: random() > 0.35,
  });
}

export function createSeed() {
  const left = Math.random().toString(36).slice(2, 6);
  const right = Math.random().toString(36).slice(2, 6);
  return `${left}-${right}`;
}

function pick(items, random) {
  return items[Math.floor(random() * items.length)];
}

function randomInt(random, min, max) {
  return Math.floor(random() * (max - min + 1)) + min;
}

function createSeededRandom(seed) {
  let hash = 2166136261;
  const source = String(seed || 'sacred-geometry');

  for (let index = 0; index < source.length; index += 1) {
    hash ^= source.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }

  return function seededRandom() {
    hash += 0x6d2b79f5;
    let value = hash;
    value = Math.imul(value ^ (value >>> 15), value | 1);
    value ^= value + Math.imul(value ^ (value >>> 7), value | 61);
    return ((value ^ (value >>> 14)) >>> 0) / 4294967296;
  };
}
